AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  DemoDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DDB_Table 
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "ID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ID"
          KeyType: "HASH"

  DemoLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: DDB_Table 
      CodeUri: example/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Visits:
          Type: Api
          Properties:
            Path: /visit
            Method: post 

  DemoWebsite:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
      BucketName: EXAMPLE_BUCKET

  BucketPolicy:
   Type: AWS::S3::BucketPolicy
   Properties:
     PolicyDocument:
       Id: Example_Policy
       Version: 2012-10-17
       Statement:
         - Sid: PublicReadForGetBucketObjects
           Effect: Allow
           Principal: "*"
           Action: "s3:GetObject"
           Resource: !Join
             - ""
             - - "arn:aws:s3:::"
               - !Ref DemoWebsite 
               - /*
     Bucket: !Ref DemoWebsite 

  DemoDistribution:
   Type: "AWS::CloudFront::Distribution"
   Properties:
     DistributionConfig:
       ViewerCertificate:
         AcmCertificateArn: !Ref DemoCertificate
         SslSupportMethod: sni-only
       Aliases:
         - EXAMPLE_ALIAS  
       DefaultCacheBehavior:
         ViewerProtocolPolicy: redirect-to-https
         TargetOriginId: S3_BUCKET_WEBSITE_ENDPOINT
         DefaultTTL: 0
         MinTTL: 0
         MaxTTL: 0
         ForwardedValues:
           QueryString: false
       Origins:
         - DomainName: S3_BUCKET_WEBSITE_ENDPOINT
           Id: YS3_BUCKET_WEBSITE_ENDPOINT
           CustomOriginConfig:
             OriginProtocolPolicy: http-only
       Enabled: "true"
       DefaultRootObject: index.html

  DemoCertificate: 
     Type: AWS::CertificateManager::Certificate
     Properties:
       DomainName: WEBSITE_NAME 
       ValidationMethod: DNS

Outputs:
  DemoLambdaFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for DemoLambdaFunction" 
    Value: !Sub API_ENDPOINT 
  DemoLambdaFunction:
    Description: "DemoLambdaFunction ARN"
    Value: !GetAtt DemoLambdaFunction.Arn 
  DemoLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for DemoLambdaFunction" 
    Value: !GetAtt DemoLambdaFunction.Arn 